# Generated by Django 5.1.7 on 2025-03-28 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='has_root',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='checkin',
            name='pseudo_timestamp',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='checkin',
            name='uptime',
            field=models.CharField(default='', max_length=100),
        ),
    ]
