# Generated by Django 5.1.7 on 2025-03-28 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl', '0002_checkin_has_root_checkin_pseudo_timestamp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnknownComputer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_id', models.CharField(max_length=40)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
