# Generated by Django 5.1.7 on 2025-03-28 20:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl', '0003_unknowncomputer'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('run_as', models.CharField(max_length=16)),
                ('payload', models.TextField()),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateTimeField(auto_now_add=True)),
                ('fetched', models.DateTimeField(null=True)),
                ('completed', models.DateTimeField(null=True)),
                ('runtime', models.FloatField(null=True)),
                ('exit_code', models.IntegerField(null=True)),
                ('stdout', models.TextField(null=True)),
                ('stderr', models.TextField(null=True)),
                ('computer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctrl.computer')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ctrl.task')),
            ],
        ),
    ]
