# Generated by Django 5.1.7 on 2025-03-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl', '0005_alter_ticket_completed_alter_ticket_exit_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='stderr',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='stdout',
            field=models.TextField(blank=True, default=''),
        ),
    ]
