# Generated by Django 5.1.7 on 2025-03-29 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl', '0006_alter_ticket_stderr_alter_ticket_stdout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='computer',
            name='machine_id',
            field=models.CharField(db_index=True, max_length=40),
        ),
    ]
