# Generated by Django 5.2.12 on 2026-07-05 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ctrl', '0011_task_presets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('cms_username', models.CharField(db_index=True, max_length=64, unique=True)),
                ('computers', models.ManyToManyField(blank=True, related_name='students', to='ctrl.computer')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='ctrl.location')),
            ],
            options={
                'ordering': ['location__sequence_num', 'name'],
            },
        ),
    ]
